const icons = {
  bar: require("./bar.svg"),
  search: require("./search.svg"),
  setting: require("./setting.svg"),
  time: require("./time.svg"),
  wavesurfer: require("./wavesurfer.svg"),
  loudspeaker: require("./loudspeaker.svg"),
  message: require("./message.svg"),
  "apple-logo": require("./apple-logo.svg"),
  "arrow-right-long-thick": require("./arrow-right-long-thick.svg"),
  "arrow-right-long": require("./arrow-right-long.svg"),
  "chevron-down-big-black": require("./chevron-down-big-black.svg"),
  "chevron-down-black": require("./chevron-down-black.svg"),
  "chevron-down": require("./chevron-down.svg"),
  "facebook-black": require("./facebook-black.svg"),
  "google-logo": require("./google-logo.svg"),
  "linked-in-black": require("./linked-in-black.svg"),
  "slack-logo": require("./slack-logo.svg"),
  "slack-main": require("./slack-main.svg"),
  "start-workspace": require("./start-workspace.svg"),
  "twitter-black": require("./twitter-black.svg"),
  "youtube-black": require("./youtube-black.svg"),
};

export default icons;
