# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy slack-clone.cf

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodeJS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

  install:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Install node_modules
        run: yarn

  build:
    runs-on: self-hosted
    needs: install

    steps:
      - name: Build
        run: npm run build

  publish:
    runs-on: self-hosted
    needs: build

    steps:
      - name: publish
        run: npm run publish
