# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy slack-clone.com

on:
  push:
    branches: [dev]

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodeJS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

  install:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Install node_modules
        run: npm ci

  build:
    runs-on: self-hosted
    needs: install

    steps:
      - name: Build
        run: npm run build

  publish:
    runs-on: self-hosted
    needs: build

    # steps:
    #   - name: publish
    #     run: npm run publish

  # restart:
  #   runs-on: self-hosted
  #   needs: publish

  #   steps:
  #     - name: copy
  #       run: pm2 restart m3u8handle.com
